
site_name: AI-Generated Documentation

theme:
  name: material
nav:
  - Home: index.md
  - Architecture: architecture.md
  - API Reference:
      - __init__: __init__.md
      - Generator: generator.md
      - Main: main.md
      - Parser: parser.md

