name: Generate and Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Generate Documentation Files
        run: python -m src.main generate src --output-dir docs
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      # --- THIS IS THE MISSING STEP ---
      - name: Build MkDocs Site
        run: mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # This now correctly points to the 'site' folder created by 'mkdocs build'
          publish_dir: ./site